force-app/main/default/objects/Record_History__c/Record_History__c.object-meta.xml
<CustomObject>
    <label>Record History</label>
    <nameField>
        <displayFormat>RH-{0000000}</displayFormat>
        <label>Record History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Record Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Record_History__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>Updated</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>Undeleted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Record_History__c/fields/Field__c.field-meta.xml
<CustomField>
    <fullName>Field__c</fullName>
    <label>Field</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Record_History__c/fields/New_Value_Extended__c.field-meta.xml
<CustomField>
    <fullName>New_Value_Extended__c</fullName>
    <label>New Value Extended</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Record_History__c/fields/Old_Value_Extended__c.field-meta.xml
<CustomField>
    <fullName>Old_Value_Extended__c</fullName>
    <label>Old Value Extended</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Record_History__c/fields/ParentId__c.field-meta.xml
<CustomField>
    <fullName>ParentId__c</fullName>
    <externalId>true</externalId>
    <label>ParentId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Record_History__c/fields/Record__c.field-meta.xml
<CustomField>
    <fullName>Record__c</fullName>
    <description>Record that this history is related to</description>
    <label>Record</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Record_History__c/fields/Record_Name__c.field-meta.xml
<CustomField>
    <fullName>Record_Name__c</fullName>
    <label>Record Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tracked_Field__mdt/Tracked_Field__mdt.object-meta.xml
<CustomObject>
    <label>Tracked Field</label>
    <pluralLabel>Tracked Fields</pluralLabel>
</CustomObject>

force-app/main/default/objects/Tracked_Field__mdt/fields/Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_API_Name__c</fullName>
    <label>Field API Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tracked_Field__mdt/fields/Tracked_Object__c.field-meta.xml
<CustomField>
    <fullName>Tracked_Object__c</fullName>
    <label>Tracked Object</label>
    <referenceTo>Tracked_Objects__mdt</referenceTo>
    <relationshipLabel>Tracked Fields</relationshipLabel>
    <relationshipName>Tracked_Fields</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Tracked_Object__mdt/Tracked_Object__mdt.object-meta.xml
<CustomObject>
    <label>Tracked Object</label>
    <pluralLabel>Tracked Objects</pluralLabel>
</CustomObject>

force-app/main/default/objects/Tracked_Object__mdt/fields/Parent_Reference_Field__c.field-meta.xml
<CustomField>
    <fullName>Parent_Reference_Field__c</fullName>
    <label>Parent Reference Field</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tracked_Object__mdt/fields/Track_Create__c.field-meta.xml
<CustomField>
    <fullName>Track_Create__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Track Create</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Tracked_Object__mdt/fields/Track_Delete__c.field-meta.xml
<CustomField>
    <fullName>Track_Delete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Track Delete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Tracked_Object__mdt/fields/Track_Undelete__c.field-meta.xml
<CustomField>
    <fullName>Track_Undelete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Track Undelete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/HistoryTrackingService.cls
public without sharing class HistoryTrackingService {
    
    static Map<String, String> operationTypeMap = new Map<String, String>{'AFTER_INSERT'=>'Create', 'AFTER_DELETE'=>'Delete', 'AFTER_UNDELETE'=>'Undelete'};
    public static void track(List<Sobject> newList, Map<Id, sObject> oldMap, System.TriggerOperation operationType){
        System.debug(operationType.toString());
        // Possible values of the System.TriggerOperation enum are: AFTER_INSERT, AFTER_UPDATE, AFTER_DELETE, and AFTER_UNDELETE. 
        Schema.sObjectType objectType;
        if(newList != null){
            for(SObject so : newList) {
                objectType = Id.valueOf(String.valueOf(so.get('Id'))).getSObjectType();
                break;
            }
        } else {
            for(String recId : oldMap.keySet()) {
                objectType = Id.valueOf(recId).getSObjectType();
                break;
            }
        }
        Schema.DescribeSObjectResult objectDescribe = objectType.getDescribe();
        Tracked_Object__mdt tobj = Tracked_Object__mdt.getInstance(objectDescribe.getName());
        System.debug(tobj);
        List<Record_History__c> histories = new List<Record_History__c>();
        if(operationType.toString() != 'AFTER_UPDATE'){
            if(tobj.Parent_Reference_Field__c != null){
                String operationEvent = operationTypeMap.get(operationType.toString());
                if((tobj.Track_Create__c && operationEvent == 'Create') || (tobj.Track_Delete__c && operationEvent == 'Delete') || (tobj.Track_Undelete__c && operationEvent == 'Undelete')){
                    List<SObject> recordList = newList != null ? newList : oldMap.values();
                    for(Sobject so : recordList){
                        String recordId = String.valueOf(so.get('Id'));
                        String recordName = so.get('Name') != null ? String.valueOf(so.get('Name')) : null;
                        Record_History__c rh = new Record_History__c();
                        rh.Event__c = operationEvent;
                        rh.Record__c = recordId;
                        rh.Record_Name__c = recordName;
                        rh.ParentId__c = String.valueOf(so.get(tobj.Parent_Reference_Field__c));
                        histories.add(rh);
                    }
                }
            }
        } else {
            Map<String,Schema.SObjectField> mfields = objectDescribe.fields.getMap();
            Map<String, Schema.DescribeFieldResult> fieldMap = new Map<String, Schema.DescribeFieldResult>();
            for(Tracked_Field__mdt field : [SELECT Field_API_Name__c FROM Tracked_Field__mdt WHERE Tracked_Object__c = :tobj.Id]) {
                fieldMap.put(field.Field_API_Name__c, mfields.get(field.Field_API_Name__c).getDescribe());
            }
            for(Sobject so : newList){
                for(String field : fieldMap.keySet()){
                    Schema.DescribeFieldResult fieldResult = fieldMap.get(field);
                    //logic dependent on field type
                    String recordId = String.valueOf(so.get('Id'));
                    String newValue = String.valueOf(so.get(field));
                    String oldValue = String.valueOf(oldMap.get(recordId).get(field));
                    if(newValue <> oldValue){
                        Record_History__c rh = new Record_History__c();
                        rh.Event__c = 'Updated';
                        rh.Field__c = fieldResult.getLabel();
                        rh.New_Value__c = newValue.left(255);
                        rh.Old_Value__c = oldValue.left(255);
                        if(newValue.length() > 255 || oldValue.length() > 255){
                            rh.New_Value_Extended__c = newValue;
                            rh.Old_Value_Extended__c = oldValue;
                        }
                        rh.Record__c = recordId;
                        histories.add(rh);
                    }
                }
            }
        }
        if(!histories.isEmpty()) insert histories;
    }
}