force-app/main/default/objects/Record_History__c/Record_History__c.object-meta.xml
<CustomObject>
    <label>Record History</label>
    <nameField>
        <displayFormat>RH-{0000000}</displayFormat>
        <label>Record History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Record Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Record_History__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>Updated</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>Undeleted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Record_History__c/fields/ParentId__c.field-meta.xml
<CustomField>
    <fullName>ParentId__c</fullName>
    <externalId>true</externalId>
    <label>ParentId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Record_History__c/fields/Record__c.field-meta.xml
<CustomField>
    <fullName>Record__c</fullName>
    <description>Record that this history is related to</description>
    <label>Record</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Record_History__c/fields/Record_Name__c.field-meta.xml
<CustomField>
    <fullName>Record_Name__c</fullName>
    <label>Record Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ImportControllerTest.cls
/**
 * @description     test for Import Controller
 * @author          Mark Meyer
 * @date            09/27/2024
 */
@isTest
public class ImportControllerTest {

    /**
     * @description     test all methods
     */
    @isTest public static void testInit(){
        Account acc = new Account(Name = 'test');
        insert acc;
        Account acc1 = new Account(Name = 'test2');
        insert acc1;
        Contact cnt = new Contact(LastName = 'test', AccountId = acc.Id);
        insert cnt;
        List<TrackingWrapper> wrapper = ImportController.getRecords();
        ObjectDetailsWrapper objectDetails = ImportController.getObjectDetails('Account');
        Integer recordCount = ImportController.getRecordCount('Account');
        List<ResultsWrapper> results = ImportController.getSelectedObjectRecords('Account');
        Record_History__c rh = new Record_History__c();
        rh.Record__c = cnt.Id;
        rh.Record_Name__c = cnt.LastName;
        rh.ParentId__c = acc.Id;
        rh.Event__c = 'Updated';
        recordCount = ImportController.generateHistoryRecords(JSON.serialize(new List<Record_History__c>{rh}));
    }
}